name: Fetch Instagram Posts Data

on:
  workflow_dispatch:

jobs:
  fetch-posts-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Instagram posts script
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        INSTAGRAM_ACCOUNT_ID: ${{ secrets.INSTAGRAM_ACCOUNT_ID }}
      run: python instagram_posts_data.py

    - name: Debug file content
      run: cat instagram_posts_data.csv || echo "Файл не найден или пуст."

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add instagram_posts_data.csv || echo "Файл не найден, пропускаем add"
        git commit -m 'Updated Instagram posts data' || echo "Нет изменений для commit"
        git push || echo "Нет изменений для push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
