name: Fetch Instagram Data

on:
  workflow_dispatch:

jobs:
  fetch-instagram-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Run instagram_daily_aggregated_data.py
    - name: Run Instagram daily aggregated script
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        INSTAGRAM_ACCOUNT_ID: ${{ secrets.INSTAGRAM_ACCOUNT_ID }}
      run: python instagram_daily_aggregated_data.py

    # Run instagram_posts_data.py
    - name: Run Instagram posts script
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        INSTAGRAM_ACCOUNT_ID: ${{ secrets.INSTAGRAM_ACCOUNT_ID }}
      run: python instagram_posts_data.py

    # Run instagram_stories_data.py
    - name: Run Instagram stories script
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        INSTAGRAM_ACCOUNT_ID: ${{ secrets.INSTAGRAM_ACCOUNT_ID }}
      run: python instagram_stories_data.py

    - name: Commit and push changes
      if: success()
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add instagram_daily_aggregated_data.csv || echo "Файл instagram_daily_aggregated_data.csv не найден, пропускаем commit"
        git add instagram_posts_data.csv || echo "Файл instagram_posts_data.csv не найден, пропускаем commit"
        git add instagram_stories_data.csv || echo "Файл instagram_stories_data.csv не найден, пропускаем commit"
        git commit -m 'Updated Instagram data files' || echo "Нет изменений для commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
